### ISSUE TITLE
Crash on First time startup

### ISSUE THREAD

**Issue by SkyGravy** [Biochao/Mechanical-Automata#4]
http://pastebin.com/bqbvB3dy

My Game Crashed on Start up first time trying to load the mod pack.

i'm running win 8.1 pro, with a strong setup.

i have tried several times first installing FTB launcher on seperate hdd and then after on primary hdd where OS is installed, 

i have tried installing it under third party pack and under FTB modpacks, 

the crash report starts at Line: 3230 in the Log

**Comment by Biochao** [comment]
Java 8 is required to play this pack because of Matter Overdrive. If you can't or don't want to update Java just remove Matter Overdrive.

**Comment by SkyGravy** [comment]
awesome thanks it worked!! had java 8 update 45 fixed by updating to update 60
