### ISSUE TITLE
Modpack crash on startup

### ISSUE THREAD

**Issue by Deadbolt602** [Biochao/Mechanical-Automata#5]
Hello,
It appears anytime that I launch the mod the FTB launcher processes it as normal until the Mojang splash screen, where at it will reach the sixth initializing mods phase and then promptly close and return to the launcher. I have tried to utilize both Java 7 update 79 and Java 8 update 60 and have tried disabling Matter Overdrive as I had seen it stated in a previous issue post that it could cause problems. However none of these fixes have worked and I am at a loss of what to do next. I should also state that I have tried force updating to no avail, and have gotten the mod pack to work at least once before this issue started. I look forward to any help that can be provided.

FTB Log: http://paste.feed-the-beast.com/view/fa244670

**Comment by Joust1187** [comment]
I'm having the same issue with BlockProperties erroring out.

**Comment by Biochao** [comment]
Delete "residual_heat.json" in "\config\BlockProperties\Railcraft\"

I forgot to delete it after I disabled the block. I wish Block Properties wouldn't crash if it found an extra block.

**Comment by Deadbolt602** [comment]
Thank you for the reply, unfortunately I'm away from my pc at the moment so I'll have to try this in the morning. I'll let you know how it goes.

**Comment by Deadbolt602** [comment]
Well I've tired deleting "residual_heat.json" and it has not helped. The game still crashes at the same point as before, additionally I've also tried disabling the railcraft mod entirely and that has still not helped.

**Comment by Deadbolt602** [comment]
Disregard that last statement, after messing around and re enabling Matter Overdrive it seems to have fixed the issue. Thank you again for the fix.

**Comment by Biochao** [comment]
Yeah, whenever a mod is removed or blocks are missing Block Properties will crash on startup until the json files are deleted.
