### ISSUE TITLE
Copper Blocks won't turn into Copper Ingots

### ISSUE THREAD

**Issue by Matunascraft** [Biochao/Mechanical-Automata#6]
Copper Blocks can be formed by smelting or by crafting. But I was unable to convert the Blocks back into Ingots. I haven't discovered any other Ingot/Blocks with this problem yet.

**Comment by Biochao** [comment]
I was experimenting with Nugget/Ingot/Block unification.
Thought I had removed my tests but there is some leftover code in Minetweaker Recipe Maker's script file.
